
file copy -force C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/csr_mlab.mif ./
file copy -force C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/debug_rom.mif ./

vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv" -work error_adapter_0                               
vcom       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_reset_controller.vhd"                                   -work niosv_reset_controller                        
vcom       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_mm_interconnect_0_avalon_st_adapter.vhd"                -work avalon_st_adapter                             
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_mm_interconnect_0_rsp_mux_002.sv"                       -work rsp_mux_002                                   
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_merlin_arbitrator.sv"                                  -work rsp_mux_002                                   
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_mm_interconnect_0_rsp_mux.sv"                           -work rsp_mux                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_merlin_arbitrator.sv"                                  -work rsp_mux                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_mm_interconnect_0_rsp_demux_001.sv"                     -work rsp_demux_001                                 
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_mm_interconnect_0_cmd_mux_001.sv"                       -work cmd_mux_001                                   
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_merlin_arbitrator.sv"                                  -work cmd_mux_001                                   
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_mm_interconnect_0_cmd_mux.sv"                           -work cmd_mux                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_merlin_arbitrator.sv"                                  -work cmd_mux                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_mm_interconnect_0_cmd_demux_002.sv"                     -work cmd_demux_002                                 
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_mm_interconnect_0_cmd_demux.sv"                         -work cmd_demux                                     
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_merlin_traffic_limiter.sv"                             -work intel_niosv_m_0_instruction_manager_wr_limiter
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_merlin_reorder_memory.sv"                              -work intel_niosv_m_0_instruction_manager_wr_limiter
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_avalon_sc_fifo.v"                                      -work intel_niosv_m_0_instruction_manager_wr_limiter
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_avalon_st_pipeline_base.v"                             -work intel_niosv_m_0_instruction_manager_wr_limiter
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_mm_interconnect_0_router_005.sv"                        -work router_005                                    
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_mm_interconnect_0_router_004.sv"                        -work router_004                                    
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_mm_interconnect_0_router_002.sv"                        -work router_002                                    
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_mm_interconnect_0_router.sv"                            -work router                                        
vlog -v2k5 "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_avalon_sc_fifo.v"                                      -work intel_niosv_m_0_dm_agent_agent_rsp_fifo       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_merlin_slave_agent.sv"                                 -work intel_niosv_m_0_dm_agent_agent                
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_merlin_burst_uncompressor.sv"                          -work intel_niosv_m_0_dm_agent_agent                
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_merlin_axi_master_ni.sv"                               -work intel_niosv_m_0_data_manager_agent            
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_merlin_address_alignment.sv"                           -work intel_niosv_m_0_data_manager_agent            
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_merlin_slave_translator.sv"                            -work intel_niosv_m_0_dm_agent_translator           
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_intel_niosv_m_0_irq_mapper.sv"                          -work irq_mapper                                    
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_dm_def.sv"                                        -work dbg_mod                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_ram.sv"                                           -work dbg_mod                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_dm_jtag2mm.sv"                                    -work dbg_mod                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_dm_top.sv"                                        -work dbg_mod                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_debug_module.sv"                                  -work dbg_mod                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_debug_rom.sv"                                     -work dbg_mod                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_std_synchronizer_bundle.v"                             -work dbg_mod                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_std_synchronizer_nocut.v"                              -work dbg_mod                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_std_synchronizer.v"                                    -work dbg_mod                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_avalon_st_clock_crosser.v"                             -work dbg_mod                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_avalon_st_handshake_clock_crosser.v"                   -work dbg_mod                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_avalon_st_pipeline_base.v"                             -work dbg_mod                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_avalon_st_pipeline_stage.sv"                           -work dbg_mod                                       
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_timer_msip.sv"                                    -work timer_module                                  
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/riscv.pkg.sv"                                           -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_opcode_def.sv"                                    -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_clic_pkg.sv"                                      -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_mem_op_state.sv"                                  -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_ram.sv"                                           -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/ecc_enc.sv"                                             -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/ecc_dec.sv"                                             -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/altecc_enc.sv"                                          -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/altecc_dec.sv"                                          -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_reg_file.sv"                                      -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_csr.sv"                                           -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_csrind_if.sv"                                     -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_csrind_host.sv"                                   -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_interrupt_handler.sv"                             -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_instr_buffer.sv"                                  -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_bus_req.sv"                                       -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_shift.sv"                                         -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_alu.sv"                                           -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_lsu.sv"                                           -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_c_decoder.sv"                                     -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_c_core.sv"                                        -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_c_csr.sv"                                         -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_c_D_stage.sv"                                     -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_c_E_stage.sv"                                     -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_c_M0_stage.sv"                                    -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_m_decoder.sv"                                     -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_m_core.sv"                                        -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_m_instr_prefetch.sv"                              -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_m_D_stage.sv"                                     -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_m_E_stage.sv"                                     -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_m_M0_stage.sv"                                    -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_m_W_stage.sv"                                     -work hart                                          
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/aldec/niosv_intel_niosv_m_0_hart.sv"                          -work hart                                          
vlog -v2k5 "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_reset_controller.v"                                    -work rst_controller                                
vlog -v2k5 "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/altera_reset_synchronizer.v"                                  -work rst_controller                                
vlog       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_irq_mapper.sv"                                          -work irq_mapper                                    
vlog -v2k5 "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_mm_interconnect_0.v"                                    -work mm_interconnect_0                             
vcom       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_pio_0.vhd"                                              -work pio_0                                         
vcom       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_onchip_memory2_0.vhd"                                   -work onchip_memory2_0                              
vlog -v2k5 "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/submodules/niosv_intel_niosv_m_0.v"                                      -work intel_niosv_m_0                               
vcom       "C:/Users/adria/OneDrive/Desktop/progettiQuartus/niosv/niosv/simulation/niosv.vhd"                                                                                                                   
